services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:1.19.6-alpine
    depends_on:
      - php-fpm
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./src:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_USER: ${POSTGRES_USER:-test_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_db_password}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}

  db:
    container_name: ${APP_NAME}_db
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_USER: ${POSTGRES_USER:-test_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_db_password}
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
      image: redis:7.4.2
      volumes:
        - redis:/data
      ports:
        - ${REDIS_PORT:-6379}:6379

volumes:
  composer:
  postgres:
  redis:
